version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ledongthuc/mathgen
    steps:
      # Update source and dependencies
      - checkout
      - run: go get -v -t -d ./...

      # Lint, test, review code
      - run: go test -v ./...

      # Build and push docker image
      - setup_remote_docker:
        docker_layer_caching: true
      - run: |
        TAG=0.0.$CIRCLE_BUILD_NUM
        docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$TAG -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest .
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$TAG
        docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest

      # Trigger deployment
