version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ledongthuc/mathgen
    steps:
      # Update source and dependencies
      - checkout
      - run: go get -v -t -d ./...

      # Lint, test, review code
      - run: go test -v ./...

      # Build and push docker image
      - setup_remote_docker
          # docker_layer_caching: true
      - run: |
          TAG=0.0.$CIRCLE_BUILD_NUM
          docker build -t $CIRCLE_PROJECT_USERNAME/$DOCKER_APP_NAME:$TAG -t $CIRCLE_PROJECT_USERNAME/$DOCKER_APP_NAME:latest .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $CIRCLE_PROJECT_USERNAME/$DOCKER_APP_NAME:$TAG
          docker push $CIRCLE_PROJECT_USERNAME/$DOCKER_APP_NAME:latest

      # Trigger deployment
      - digitalocean-orb/install
      - digitalocean-orb/initialize:
          cluster: $K8S_CLUSTER_NAME
          digitalocean-access-token: DIGITALOCEAN_ACCESS_TOKEN
      - run: |
          cp ./web/k8s/secret.yaml.template ./secret.yaml
          sed 's/_ENV_VAR_/$CHROME_ORIGIN_TRIAL/g' ./secret.yaml
          kubectl apply -f ./secret.yaml
          rm ./secret.yaml
          TAG=0.0.$CIRCLE_BUILD_NUM
          kubectl set image deployment/$K8S_DEPLOYMENT_NAME $K8S_POD_NAME=$CIRCLE_PROJECT_USERNAME/$DOCKER_APP_NAME:$TAG
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
orbs:
  digitalocean-orb: digitalocean/k8s@0.1.1
