name: deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.2'
    - name: test
      run: go test ./...
    - name: Run build
      run: go build -o ./release/mathgen-web -v ./web/main.go
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2  
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ledongthuc/mathgen-web:latest
    - name: Push
      run: docker push ledongthuc/mathgen-web:latest
